# Generated by Django 5.2.5 on 2026-03-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_found/'),
        ),
    ]
