# Generated by Django 5.2.5 on 2026-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_lostfounditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfounditem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
