# Generated by Django 5.2.5 on 2026-03-06 07:53

from django.db import migrations, models


def copy_contact_info_to_primary_phone(apps, schema_editor):
    LostFoundItem = apps.get_model('lost_found', 'LostFoundItem')
    for item in LostFoundItem.objects.all():
        if not getattr(item, 'primary_phone', '') and getattr(item, 'contact_info', ''):
            item.primary_phone = item.contact_info[:20]
            item.save(update_fields=['primary_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0003_alter_lostfounditem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='primary_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(copy_contact_info_to_primary_phone, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='lostfounditem',
            name='contact_info',
        ),
    ]
