# Generated by Django 5.2.5 on 2026-03-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0004_remove_lostfounditem_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lost_found/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lost_found.lostfounditem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
