# Generated by Django 5.2.5 on 2026-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_proposals/'),
        ),
    ]
