# Generated by Django 5.2.5 on 2025-09-02 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('approver_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Approval Request',
                'verbose_name_plural': 'Admin Approval Requests',
                'indexes': [models.Index(fields=['department', 'approved'], name='authenticat_departm_edb070_idx')],
            },
        ),
    ]
