# Generated by Django 5.2.5 on 2026-03-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_adminapprovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_class_representative',
            field=models.BooleanField(default=False),
        ),
    ]
