# Generated by Django 5.2.5 on 2026-03-06 07:41

from django.db import migrations, models


def convert_faculty_to_student(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    User.objects.filter(role='faculty').update(role='student', is_class_representative=False)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_class_representative'),
    ]

    operations = [
        migrations.RunPython(convert_faculty_to_student, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
