# Generated by Django 5.2.5 on 2026-03-06 09:35

from django.db import migrations, models


def migrate_breakfast_values(apps, schema_editor):
    MessFeedback = apps.get_model('mess_feedback', 'MessFeedback')
    MessFeedback.objects.filter(meal_type='breakfast').update(meal_type='breakfast_tiffins')


class Migration(migrations.Migration):

    dependencies = [
        ('mess_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_breakfast_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='messfeedback',
            name='meal_type',
            field=models.CharField(choices=[('breakfast_tiffins', 'Breakfast - Tiffins'), ('breakfast_beverages', 'Breakfast - Beverages'), ('breakfast_other', 'Breakfast - Other'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20),
        ),
    ]
