# Generated by Django 5.2.5 on 2026-03-06 09:39

from django.db import migrations, models


def migrate_meal_type_to_subtype(apps, schema_editor):
    MessFeedback = apps.get_model('mess_feedback', 'MessFeedback')

    MessFeedback.objects.filter(meal_type='breakfast_tiffins').update(
        meal_type='breakfast',
        meal_subtype='tiffins'
    )
    MessFeedback.objects.filter(meal_type='breakfast_beverages').update(
        meal_type='breakfast',
        meal_subtype='beverages'
    )
    MessFeedback.objects.filter(meal_type='breakfast_other').update(
        meal_type='breakfast',
        meal_subtype='other'
    )

    MessFeedback.objects.filter(meal_type='lunch', meal_subtype='').update(meal_subtype='rice')
    MessFeedback.objects.filter(meal_type='dinner', meal_subtype='').update(meal_subtype='rice')
    MessFeedback.objects.filter(meal_type='snack', meal_subtype='').update(meal_subtype='tea')
    MessFeedback.objects.filter(meal_type='breakfast', meal_subtype='').update(meal_subtype='tiffins')


class Migration(migrations.Migration):

    dependencies = [
        ('mess_feedback', '0002_alter_messfeedback_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messfeedback',
            name='meal_subtype',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RunPython(migrate_meal_type_to_subtype, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='messfeedback',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20),
        ),
    ]
