# Generated by Django 5.2.5 on 2026-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_feedback', '0003_messfeedback_meal_subtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messfeedback',
            name='meal_subtype_custom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
