# Generated by Django 5.2.5 on 2026-03-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_feedback', '0005_messfeedback_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessFeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mess_feedback/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mess_feedback.messfeedback')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
